//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab7b_client.WS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Note", Namespace="http://svv.org/")]
    [System.SerializableAttribute()]
    public partial class Note : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long NoteIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelephoneField;

        public Note(string name, string num)
        {
            this.Telephone = num;
            this.Fullname = name;
            this.NoteId = DateTime.Now.ToFileTime();
        }
        public Note(long id, string name, string num)
        {
            this.NoteId = id;
            this.Fullname = name;
            this.Telephone = num;
        }

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long NoteId {
            get {
                return this.NoteIdField;
            }
            set {
                if ((this.NoteIdField.Equals(value) != true)) {
                    this.NoteIdField = value;
                    this.RaisePropertyChanged("NoteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Fullname {
            get {
                return this.FullnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullnameField, value) != true)) {
                    this.FullnameField = value;
                    this.RaisePropertyChanged("Fullname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Telephone {
            get {
                return this.TelephoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TelephoneField, value) != true)) {
                    this.TelephoneField = value;
                    this.RaisePropertyChanged("Telephone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://svv.org/", ConfigurationName="WS.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Контракт генерации сообщений с именем GetDictResult из пространства имен http://svv.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://svv.org/GetDict", ReplyAction="*")]
        Lab7b_client.WS.GetDictResponse GetDict(Lab7b_client.WS.GetDictRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://svv.org/GetDict", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab7b_client.WS.GetDictResponse> GetDictAsync(Lab7b_client.WS.GetDictRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем newNote из пространства имен http://svv.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://svv.org/AddDict", ReplyAction="*")]
        Lab7b_client.WS.AddDictResponse AddDict(Lab7b_client.WS.AddDictRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://svv.org/AddDict", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab7b_client.WS.AddDictResponse> AddDictAsync(Lab7b_client.WS.AddDictRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем newNote из пространства имен http://svv.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://svv.org/UpdDict", ReplyAction="*")]
        Lab7b_client.WS.UpdDictResponse UpdDict(Lab7b_client.WS.UpdDictRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://svv.org/UpdDict", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab7b_client.WS.UpdDictResponse> UpdDictAsync(Lab7b_client.WS.UpdDictRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://svv.org/DelDict", ReplyAction="*")]
        long DelDict(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://svv.org/DelDict", ReplyAction="*")]
        System.Threading.Tasks.Task<long> DelDictAsync(long id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDictRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDict", Namespace="http://svv.org/", Order=0)]
        public Lab7b_client.WS.GetDictRequestBody Body;
        
        public GetDictRequest() {
        }
        
        public GetDictRequest(Lab7b_client.WS.GetDictRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDictRequestBody {
        
        public GetDictRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDictResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDictResponse", Namespace="http://svv.org/", Order=0)]
        public Lab7b_client.WS.GetDictResponseBody Body;
        
        public GetDictResponse() {
        }
        
        public GetDictResponse(Lab7b_client.WS.GetDictResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://svv.org/")]
    public partial class GetDictResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Lab7b_client.WS.Note[] GetDictResult;
        
        public GetDictResponseBody() {
        }
        
        public GetDictResponseBody(Lab7b_client.WS.Note[] GetDictResult) {
            this.GetDictResult = GetDictResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDictRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDict", Namespace="http://svv.org/", Order=0)]
        public Lab7b_client.WS.AddDictRequestBody Body;
        
        public AddDictRequest() {
        }
        
        public AddDictRequest(Lab7b_client.WS.AddDictRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://svv.org/")]
    public partial class AddDictRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Lab7b_client.WS.Note newNote;
        
        public AddDictRequestBody() {
        }
        
        public AddDictRequestBody(Lab7b_client.WS.Note newNote) {
            this.newNote = newNote;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDictResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDictResponse", Namespace="http://svv.org/", Order=0)]
        public Lab7b_client.WS.AddDictResponseBody Body;
        
        public AddDictResponse() {
        }
        
        public AddDictResponse(Lab7b_client.WS.AddDictResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://svv.org/")]
    public partial class AddDictResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Lab7b_client.WS.Note AddDictResult;
        
        public AddDictResponseBody() {
        }
        
        public AddDictResponseBody(Lab7b_client.WS.Note AddDictResult) {
            this.AddDictResult = AddDictResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdDictRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdDict", Namespace="http://svv.org/", Order=0)]
        public Lab7b_client.WS.UpdDictRequestBody Body;
        
        public UpdDictRequest() {
        }
        
        public UpdDictRequest(Lab7b_client.WS.UpdDictRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://svv.org/")]
    public partial class UpdDictRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Lab7b_client.WS.Note newNote;
        
        public UpdDictRequestBody() {
        }
        
        public UpdDictRequestBody(Lab7b_client.WS.Note newNote) {
            this.newNote = newNote;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdDictResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdDictResponse", Namespace="http://svv.org/", Order=0)]
        public Lab7b_client.WS.UpdDictResponseBody Body;
        
        public UpdDictResponse() {
        }
        
        public UpdDictResponse(Lab7b_client.WS.UpdDictResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://svv.org/")]
    public partial class UpdDictResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Lab7b_client.WS.Note UpdDictResult;
        
        public UpdDictResponseBody() {
        }
        
        public UpdDictResponseBody(Lab7b_client.WS.Note UpdDictResult) {
            this.UpdDictResult = UpdDictResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : Lab7b_client.WS.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<Lab7b_client.WS.WebServiceSoap>, Lab7b_client.WS.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab7b_client.WS.GetDictResponse Lab7b_client.WS.WebServiceSoap.GetDict(Lab7b_client.WS.GetDictRequest request) {
            return base.Channel.GetDict(request);
        }
        
        public Lab7b_client.WS.Note[] GetDict() {
            Lab7b_client.WS.GetDictRequest inValue = new Lab7b_client.WS.GetDictRequest();
            inValue.Body = new Lab7b_client.WS.GetDictRequestBody();
            Lab7b_client.WS.GetDictResponse retVal = ((Lab7b_client.WS.WebServiceSoap)(this)).GetDict(inValue);
            return retVal.Body.GetDictResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab7b_client.WS.GetDictResponse> Lab7b_client.WS.WebServiceSoap.GetDictAsync(Lab7b_client.WS.GetDictRequest request) {
            return base.Channel.GetDictAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab7b_client.WS.GetDictResponse> GetDictAsync() {
            Lab7b_client.WS.GetDictRequest inValue = new Lab7b_client.WS.GetDictRequest();
            inValue.Body = new Lab7b_client.WS.GetDictRequestBody();
            return ((Lab7b_client.WS.WebServiceSoap)(this)).GetDictAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab7b_client.WS.AddDictResponse Lab7b_client.WS.WebServiceSoap.AddDict(Lab7b_client.WS.AddDictRequest request) {
            return base.Channel.AddDict(request);
        }
        
        public Lab7b_client.WS.Note AddDict(Lab7b_client.WS.Note newNote) {
            Lab7b_client.WS.AddDictRequest inValue = new Lab7b_client.WS.AddDictRequest();
            inValue.Body = new Lab7b_client.WS.AddDictRequestBody();
            inValue.Body.newNote = newNote;
            Lab7b_client.WS.AddDictResponse retVal = ((Lab7b_client.WS.WebServiceSoap)(this)).AddDict(inValue);
            return retVal.Body.AddDictResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab7b_client.WS.AddDictResponse> Lab7b_client.WS.WebServiceSoap.AddDictAsync(Lab7b_client.WS.AddDictRequest request) {
            return base.Channel.AddDictAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab7b_client.WS.AddDictResponse> AddDictAsync(Lab7b_client.WS.Note newNote) {
            Lab7b_client.WS.AddDictRequest inValue = new Lab7b_client.WS.AddDictRequest();
            inValue.Body = new Lab7b_client.WS.AddDictRequestBody();
            inValue.Body.newNote = newNote;
            return ((Lab7b_client.WS.WebServiceSoap)(this)).AddDictAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab7b_client.WS.UpdDictResponse Lab7b_client.WS.WebServiceSoap.UpdDict(Lab7b_client.WS.UpdDictRequest request) {
            return base.Channel.UpdDict(request);
        }
        
        public Lab7b_client.WS.Note UpdDict(Lab7b_client.WS.Note newNote) {
            Lab7b_client.WS.UpdDictRequest inValue = new Lab7b_client.WS.UpdDictRequest();
            inValue.Body = new Lab7b_client.WS.UpdDictRequestBody();
            inValue.Body.newNote = newNote;
            Lab7b_client.WS.UpdDictResponse retVal = ((Lab7b_client.WS.WebServiceSoap)(this)).UpdDict(inValue);
            return retVal.Body.UpdDictResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab7b_client.WS.UpdDictResponse> Lab7b_client.WS.WebServiceSoap.UpdDictAsync(Lab7b_client.WS.UpdDictRequest request) {
            return base.Channel.UpdDictAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab7b_client.WS.UpdDictResponse> UpdDictAsync(Lab7b_client.WS.Note newNote) {
            Lab7b_client.WS.UpdDictRequest inValue = new Lab7b_client.WS.UpdDictRequest();
            inValue.Body = new Lab7b_client.WS.UpdDictRequestBody();
            inValue.Body.newNote = newNote;
            return ((Lab7b_client.WS.WebServiceSoap)(this)).UpdDictAsync(inValue);
        }
        
        public long DelDict(long id) {
            return base.Channel.DelDict(id);
        }
        
        public System.Threading.Tasks.Task<long> DelDictAsync(long id) {
            return base.Channel.DelDictAsync(id);
        }
    }
}
